import type {Metadata} from 'next'
import {Poppins} from 'next/font/google'

// Styles.
import '@/styles/global.css'
import '@/styles/page/app.css'
import '@/styles/responsive/app.responsive.css'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: 'Web App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
