export {default as LeftBar} from './LeftBar'
export {default as About} from './About'
export {default as Projects} from './Projects'
export {default as Contacts} from './Contacts'
export {default as Loading} from './Loading'
